name: Infrastructure CI

on:
  push:
    paths:
      - '**.tf'
      - 'alsia/add-formatting-job'

jobs:
  format:
    name: Format Terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Format Terraform
        run: |
          terraform fmt

  verify-plan:
    name: Validate Terraform Plan
    runs-on: ubuntu-latest
    needs: [format]
    
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0
          terraform_wrapper: false
      
      - name: Terraform Init
        run: terraform init

      - name: Create Terraform execution plan
        run: |
          terraform validate
          terraform plan -out=plan.tfplan
      
      - name: Apply from execution plan
        run: terraform apply plan.tfplan
